disabled_rules:
- trailing_whitespace
- function_body_length
- type_body_length
- control_statement
- colon
#- line_length
#- file_length
- identifier_name
- redundant_string_enum_value
opt_in_rules:
- empty_count
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 200
    error: 9999999999999
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_parameter_count:
    warning: 6
    error: 8
file_length:
    warning: 1000
    error: 9999999999999
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 80
    error: 100
reporter: "xcode"
